[project]
name = "hnsdoh-status"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "apscheduler>=3.9.1",
    "brotli>=1.2.0",
    "dnslib>=0.9.26",
    "dnspython>=2.8.0",
    "flask>=3.1.2",
    "flask-caching>=2.3.1",
    "gunicorn>=23.0.0",
    "python-dateutil>=2.9.0.post0",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "schedule>=1.2.2",
]

[dependency-groups]
dev = [
    "ruff>=0.14.5",
]
